name: William Merkel
favicon: null
layout_spectrum: 0.5460382415913045
typography_spectrum: 0.7227866793982685
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.48049145052209496
  lightness: 0.08581760665401816
  saturation: 0.2393284672871232
  rhythmicContrast: 0.0972370277158916
purpose: []
